// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fsm.proto

package fsmpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MsgBeat      MessageType = 0
	MsgHeartbeat MessageType = 1
)

var MessageType_name = map[int32]string{
	0: "MsgBeat",
	1: "MsgHeartbeat",
}

var MessageType_value = map[string]int32{
	"MsgBeat":      0,
	"MsgHeartbeat": 1,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{0}
}

type Message struct {
	Type         MessageType `protobuf:"varint,1,opt,name=type,enum=fsmpb.MessageType" json:"type"`
	To           uint64      `protobuf:"varint,2,opt,name=to" json:"to"`
	From         uint64      `protobuf:"varint,3,opt,name=from" json:"from"`
	IsEtcdStoped bool        `protobuf:"varint,4,opt,name=isEtcdStoped" json:"isEtcdStoped"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MsgBeat
}

func (m *Message) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Message) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Message) GetIsEtcdStoped() bool {
	if m != nil {
		return m.IsEtcdStoped
	}
	return false
}

func init() {
	proto.RegisterEnum("fsmpb.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Message)(nil), "fsmpb.Message")
}

func init() { proto.RegisterFile("fsm.proto", fileDescriptor_ef5b9a5dc540ad10) }

var fileDescriptor_ef5b9a5dc540ad10 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2b, 0xce, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2b, 0xce, 0x2d, 0x48, 0x92, 0x12, 0x49, 0xcf,
	0x4f, 0xcf, 0x07, 0x8b, 0xe8, 0x83, 0x58, 0x10, 0x49, 0xa5, 0x89, 0x8c, 0x5c, 0xec, 0xbe, 0xa9,
	0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x3a, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x7c, 0x46, 0x42, 0x7a, 0x60, 0x7d, 0x7a, 0x50, 0xd9, 0x90, 0xca, 0x82, 0x54, 0x27,
	0x96, 0x13, 0xf7, 0xe4, 0x19, 0x82, 0xc0, 0xaa, 0x84, 0x44, 0xb8, 0x98, 0x4a, 0xf2, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x58, 0xa0, 0xe2, 0x4c, 0x25, 0xf9, 0x42, 0x12, 0x5c, 0x2c, 0x69, 0x45, 0xf9,
	0xb9, 0x12, 0xcc, 0x48, 0xe2, 0x60, 0x11, 0x21, 0x0d, 0x2e, 0x9e, 0xcc, 0x62, 0xd7, 0x92, 0xe4,
	0x94, 0xe0, 0x92, 0xfc, 0x82, 0xd4, 0x14, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x0e, 0xa8, 0x0a, 0x14,
	0x19, 0x2d, 0x1d, 0x2e, 0x6e, 0x24, 0x4b, 0x85, 0xb8, 0xb9, 0xd8, 0x7d, 0x8b, 0xd3, 0x9d, 0x52,
	0x13, 0x4b, 0x04, 0x18, 0x84, 0x04, 0xb8, 0x78, 0x7c, 0x8b, 0xd3, 0x3d, 0x52, 0x13, 0x8b, 0x4a,
	0x92, 0x40, 0x22, 0x8c, 0x4e, 0x52, 0x17, 0x1e, 0xca, 0x31, 0x4c, 0x78, 0x2c, 0xc7, 0x70, 0xe1,
	0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x1c, 0x7a, 0xfa, 0xd6, 0x60, 0xb7, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x98, 0x36, 0x54, 0xf5, 0x06, 0x01, 0x00, 0x00,
}
