// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fsm.proto

package fsmpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MsgBeat          MessageType = 0
	MsgHeartbeat     MessageType = 1
	MsgReqArbit      MessageType = 2
	MsgReqArbitResp  MessageType = 3
	MsgReleaseArbit  MessageType = 4
	MsgMemberAdd     MessageType = 5
	MsgMemberAddResp MessageType = 6
)

var MessageType_name = map[int32]string{
	0: "MsgBeat",
	1: "MsgHeartbeat",
	2: "MsgReqArbit",
	3: "MsgReqArbitResp",
	4: "MsgReleaseArbit",
	5: "MsgMemberAdd",
	6: "MsgMemberAddResp",
}

var MessageType_value = map[string]int32{
	"MsgBeat":          0,
	"MsgHeartbeat":     1,
	"MsgReqArbit":      2,
	"MsgReqArbitResp":  3,
	"MsgReleaseArbit":  4,
	"MsgMemberAdd":     5,
	"MsgMemberAddResp": 6,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{0}
}

type StateType int32

const (
	DualRunning     StateType = 0
	FaultPending    StateType = 1
	RecoveryPending StateType = 2
	SingleRunning   StateType = 3
	EtcdStoped      StateType = 4
)

var StateType_name = map[int32]string{
	0: "DualRunning",
	1: "FaultPending",
	2: "RecoveryPending",
	3: "SingleRunning",
	4: "EtcdStoped",
}

var StateType_value = map[string]int32{
	"DualRunning":     0,
	"FaultPending":    1,
	"RecoveryPending": 2,
	"SingleRunning":   3,
	"EtcdStoped":      4,
}

func (x StateType) Enum() *StateType {
	p := new(StateType)
	*p = x
	return p
}

func (x StateType) String() string {
	return proto.EnumName(StateType_name, int32(x))
}

func (x *StateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StateType_value, data, "StateType")
	if err != nil {
		return err
	}
	*x = StateType(value)
	return nil
}

func (StateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{1}
}

type Message struct {
	Type  MessageType `protobuf:"varint,1,opt,name=type,enum=fsmpb.MessageType" json:"type"`
	State StateType   `protobuf:"varint,3,opt,name=state,enum=fsmpb.StateType" json:"state"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MsgBeat
}

func (m *Message) GetState() StateType {
	if m != nil {
		return m.State
	}
	return DualRunning
}

func init() {
	proto.RegisterEnum("fsmpb.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("fsmpb.StateType", StateType_name, StateType_value)
	proto.RegisterType((*Message)(nil), "fsmpb.Message")
}

func init() { proto.RegisterFile("fsm.proto", fileDescriptor_ef5b9a5dc540ad10) }

var fileDescriptor_ef5b9a5dc540ad10 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x3b, 0x18, 0x22, 0x0f, 0x85, 0x5a, 0x39, 0x10, 0x0e, 0xd3, 0x78, 0x32, 0x84, 0x8c,
	0xc4, 0xab, 0x27, 0x88, 0x1a, 0x2f, 0x4b, 0xcc, 0xf0, 0xe4, 0xad, 0x63, 0x8f, 0x86, 0x64, 0xac,
	0x75, 0x2d, 0x26, 0x7c, 0x0a, 0xfd, 0x58, 0x1e, 0x39, 0x7a, 0x32, 0x31, 0x7c, 0x11, 0xd3, 0x0e,
	0xc8, 0x6e, 0xcd, 0xef, 0xfd, 0xfe, 0xef, 0xfd, 0x53, 0x68, 0x2d, 0xf4, 0x2a, 0x54, 0x85, 0x34,
	0x92, 0x35, 0x16, 0x7a, 0xa5, 0x92, 0x41, 0x4f, 0x48, 0x21, 0x1d, 0x19, 0xdb, 0x57, 0x39, 0xbc,
	0x41, 0x68, 0x46, 0xa8, 0x35, 0x17, 0xc8, 0x46, 0xe0, 0x9b, 0x8d, 0xc2, 0xbe, 0x77, 0xed, 0xdd,
	0x76, 0xee, 0x58, 0xe8, 0x62, 0xe1, 0x7e, 0xfa, 0xba, 0x51, 0x38, 0xf5, 0xbf, 0x7f, 0xaf, 0x48,
	0xec, 0x2c, 0x36, 0x82, 0x86, 0x36, 0xdc, 0x60, 0xbf, 0xee, 0x74, 0xba, 0xd7, 0x67, 0x96, 0x55,
	0xe4, 0x52, 0x1a, 0x7e, 0x7a, 0xd0, 0xae, 0x6c, 0x62, 0x6d, 0x68, 0x46, 0x5a, 0x4c, 0x91, 0x1b,
	0x4a, 0x18, 0x85, 0xb3, 0x48, 0x8b, 0x67, 0xe4, 0x85, 0x49, 0x2c, 0xf1, 0x58, 0x17, 0xda, 0x91,
	0x16, 0x31, 0xbe, 0x4f, 0x8a, 0x64, 0x69, 0x68, 0x8d, 0x5d, 0x42, 0xb7, 0x02, 0x62, 0xd4, 0x8a,
	0xd6, 0x8f, 0x30, 0x43, 0xae, 0xb1, 0x34, 0xfd, 0xfd, 0xb2, 0x08, 0x57, 0x09, 0x16, 0x93, 0x34,
	0xa5, 0x0d, 0xd6, 0x03, 0x5a, 0x25, 0x2e, 0x7c, 0x32, 0x5c, 0x40, 0xeb, 0xd8, 0xd5, 0xde, 0x7b,
	0x58, 0xf3, 0x2c, 0x5e, 0xe7, 0xf9, 0x32, 0x17, 0x65, 0xa5, 0x27, 0xbe, 0xce, 0xcc, 0x0b, 0xe6,
	0xa9, 0x25, 0x9e, 0x3d, 0x16, 0xe3, 0x5c, 0x7e, 0x60, 0xb1, 0x39, 0xc0, 0x1a, 0xbb, 0x80, 0xf3,
	0xd9, 0x32, 0x17, 0x19, 0x1e, 0x92, 0x75, 0xd6, 0x01, 0x78, 0x34, 0xf3, 0x74, 0x66, 0xa4, 0xc2,
	0x94, 0xfa, 0xd3, 0xc1, 0xf6, 0x2f, 0x20, 0x5f, 0xbb, 0x80, 0x6c, 0x77, 0x01, 0xf9, 0xd9, 0x05,
	0xe4, 0xed, 0x34, 0x1c, 0xdf, 0xbb, 0xcf, 0xfa, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x89, 0xcf, 0xa7,
	0x06, 0xa5, 0x01, 0x00, 0x00,
}
